language: c
compiler: gcc

services:
  - docker
 
env:
# - DOCKER_IMAGE=toopher/centos-i386:centos6 # Pull request welcome that makes this work
  - DOCKER_IMAGE=library/centos:6.8
 
script:
  - rm -rf data.tar.g* .gnu* || true
  - wget https://github.com/probonopd/AppImageKit/files/584665/data.zip -O data.tar.gz.gpg
  - ( set +x ; echo $KEY | gpg2 --batch --passphrase-fd 0 --no-tty --skip-verify --output data.tar.gz --decrypt data.tar.gz.gpg ) || true
  - ( tar xf data.tar.gz ; sudo chown -R $USER .gnu* ; rm -rf $HOME/.gnu* ; mv .gnu* $HOME/ ) || true
  - mkdir -p ./out/
  - docker run -i -v ${PWD}/out:/out -v "${PWD}:/AppImageKit" "$DOCKER_IMAGE" /bin/bash -c "cd /AppImageKit ; yum -y install sudo ; sudo ./build.sh"
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - find ./out/appimagetool.AppDir/
  - find ./out/appimaged.AppDir/
  - ( cd out/ ; ./appimagetool.AppDir/AppRun ./appimagetool.AppDir/ -s -v -u "zsync|https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage.zsync" )
  - ( cd out/ ; ./appimagetool-x86_64.AppImage ./appimaged.AppDir/ -s -v -u "zsync|https://github.com/probonopd/AppImageKit/releases/download/continuous/appimaged-x86_64.AppImage.zsync" )
  - sudo apt-get install equivs
  - ( cd out ; equivs-build ../appimaged.ctl )
  - rm -rf out/appimaged out/appimagetool out/validate out/digest out/mksquashfs || true
  - rm -rf out/runtime || true # Not needed, might confuse users
  - sudo rm -rf out/*.AppDir out/*.AppImage.digest || true # Not needed
  - bash ./upload.sh out/*

notifications:
  irc:
    channels: 
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

branches:
  except:
  - # Do not build tags that we create when we upload to GitHub Releases
  - /^(?i:continuous)$/
