language: c
compiler: gcc

services:
  - docker

env:
  - ARCH=x86_64 DOCKER_IMAGE=quay.io/appimage/appimagebuild
  - ARCH=i686 DOCKER_IMAGE=quay.io/appimage/appimagebuild-i386

script:
  - if [ "$ARCH" == "x86_64" ] ; then sed -i -e 's|%ARCH%|amd64|g' appimaged.ctl; fi
  - if [ "$ARCH" == "i686" ] ; then sed -i -e 's|%ARCH%|i386|g' appimaged.ctl && sleep 60 ; fi # Sleep so as not to overwrite during uploading (FIXME)
  - grep Architecture appimaged.ctl
  - rm -rf data.tar.g* .gnu* || true
  - wget https://github.com/AppImage/AppImageKit/files/584665/data.zip -O data.tar.gz.gpg
  - ( set +x ; echo $KEY | gpg2 --batch --passphrase-fd 0 --no-tty --skip-verify --output data.tar.gz --decrypt data.tar.gz.gpg ) || true
  - ( tar xf data.tar.gz ; sudo chown -R $USER .gnu* ; rm -rf $HOME/.gnu* ; mv .gnu* $HOME/ ) || true
  - mkdir -p ./out/
  - docker run --device /dev/fuse:mrw -e TRAVIS -i -v ${PWD}/out:/out -v "${PWD}:/AppImageKit" "$DOCKER_IMAGE" /bin/bash -xc "cd /AppImageKit && ./build.sh && ./test-appimagetool.sh build/out/usr/bin/appimagetool"
  - find ./out/appimagetool.AppDir/
  - find ./out/appimaged.AppDir/
  - docker run --cap-add SYS_ADMIN --device /dev/fuse:mrw -i -v ${PWD}/out:/out -v $HOME/.gnupg:/root/.gnupg "$DOCKER_IMAGE" /bin/bash -xc
      "cd /out &&
      ./appimagetool.AppDir/AppRun ./appimagetool.AppDir/ -s -v -u \"gh-releases-zsync|AppImage|AppImageKit|continuous|appimagetool-x86_64.AppImage.zsync\"
      appimagetool-$ARCH.AppImage &&
      ./appimagetool-$ARCH.AppImage ./appimaged.AppDir/ -s -v -u \"gh-releases-zsync|AppImage|AppImageKit|continuous|appimaged-x86_64.AppImage.zsync\" appimaged-$ARCH.AppImage"
  - sudo apt-get install equivs vim-common # vim-common contains xxd
  - ( cd out ; equivs-build ../appimaged.ctl )
  - rm -rf out/appimaged out/appimagetool out/validate out/digest out/mksquashfs || true
  - xxd out/runtime | head -n 1
  - mv out/runtime out/runtime-$ARCH
  - sudo rm -rf out/*.AppDir out/*.AppImage.digest || true # Not needed
  - if [ "$ARCH" == "x86_64" ] ; then sudo mv out/AppRun out/AppRun-x86_64; fi
  - if [ "$ARCH" == "i686" ] ; then sudo mv out/AppRun out/AppRun-i686; fi


after_success:
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh out/*

notifications:
  irc:
    channels:
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

branches:
  only:
    - appimagetool/master
    - feature/usage
