language: c
compiler: gcc

services:
 - docker
script:
 - ./build-multiarch.sh
 - wget https://raw.githubusercontent.com/probonopd/AppImages/26541d6542b7bdcca9cbd1804590862c1a935e27/bintray.sh
 - for i in out/*; do bash bintray.sh "$i"; done

before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: Rtz7d+BKUnBT8D5FoE4XXCvVhRSQVdGK/c5VpI6IYuGhwmtx4RIvK78cICFPZq8k1xJm8yOuCOChX6EyElhUkYh5iPzDI/J7IiqBl+z+/V3aXx6W2PKyYLohZW3z9iomQbX2LQ6vHcZsNqQsjKZ2dW7Ja5Q9cZTFKiokMXsAERo=
  skip_cleanup: true
  file_glob: true
  file: out/*
  on:
    tags: true
    all_branches: true
    
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
